Repository CA-G12/tariq-rabee-week6-project, pull requests merged in 2022-08, with the labels that each got.

#5 Create file structure
  .eslintrc.json
  .gitignore
  client/index.html
  client/infoPage/dom.js
  client/infoPage/index.css
  client/infoPage/index.html
  client/infoPage/index.js
  client/landingPage/dom.js
  client/landingPage/index.css
  client/landingPage/index.js
  client/mainPage/dom.js
  client/mainPage/index.css
  client/mainPage/index.html
  client/mainPage/index.js
  package-lock.json
  package.json
  server/index.js
Labels: Approved

#6 created file structure for server side
  server/Controllers/customers/getAllCustomers.js
  server/Controllers/customers/index.js
  server/Controllers/customers/postCustomer.js
  server/Controllers/index.js
  server/Controllers/meals/getAllMeals.js
  server/Controllers/meals/index.js
  server/Controllers/meals/postMeals.js
  server/Controllers/orders/getOrder.js
  server/Controllers/orders/index.js
  server/Controllers/orders/postOrder.js
  server/Database/config/conection.js
  server/Database/config/data.sql
  server/Database/query/customer.js
  server/Database/query/index.js
  server/Database/query/meals.js
  server/app.js
  server/router.js
Labels: Approved

#9 added some data in meals table
  __test__/test.js
  server/Database/config/data.sql
Labels: Approved

#11 JS Create server
  server/app.js
  server/index.js
  test/database.test.js
  test/router.test.js
  test/scirpt.test.js
Labels: Awaiting-review

#13 created pages
  client/customer/dom.js
  client/customer/index.html
  client/customer/index.js
  client/customer/style.css
  client/errors/Error404.html
  client/errors/Error500.html
  client/errors/error.css
  client/index.html
  client/landingPage/dom.js
  client/landingPage/index.css
  client/landingPage/index.js
  client/mainPage/dom.js
  client/mainPage/index.css
  client/mainPage/index.html
  client/mainPage/index.js
  client/meal/dom.js
  client/meal/index.html
  client/meal/index.js
  client/meal/style.css
  client/order/dom.js
  client/order/index.html
  client/order/index.js
  client/order/style.css
  client/style.css
Labels: Approved

#15 Write controller and query codes
  server/Controllers/customers/getAllCustomers.js
  server/Controllers/customers/index.js
  server/Database/config/conection.js
  server/Database/config/data.sql
  server/Database/query/customer.js
  server/Database/query/index.js
  server/Database/query/meals.js
  server/app.js
  server/router.js
Labels: Approved

#17 Commit ...
  server/Controllers/customers/getAllCustomers.js
  server/Controllers/customers/index.js
  server/Controllers/index.js
  server/Controllers/meals/getAllMeals.js
  server/Controllers/meals/index.js
  server/Database/config/conection.js
  server/Database/config/connection.js
  server/Database/config/data.sql
  server/Database/query/customer.js
  server/Database/query/orders.js
  server/app.js
  server/router.js
Labels: Approved

#19 Created orders functions
  .vscode/settings.json
  client/customer/dom.js
  client/customer/index.html
  package-lock.json
  package.json
  server/Controllers/customers/getAllCustomers.js
  server/Controllers/index.js
  server/Controllers/orders/getOrder.js
  server/Database/config/connection.js
  server/Database/config/data.sql
  server/Database/query/customer.js
  server/Database/query/index.js
  server/Database/query/orders.js
  server/app.js
  server/router.js
Labels: Done
